ethereum_rpc = "https://ethereum-holesky-rpc.publicnode.com"
drosera_rpc = "https://seed-node.testnet.drosera.io"
eth_chain_id = 17000
drosera_address = "0xea08f7d533C2b9A62F40D5326214f39a8E3A32F8" # holesky address

[traps]

[traps.mytrap]
path = "contracts/out/Trap.sol/Trap.json"
response_contract = "0x416aA3569F8C4C98FE3472701D89e4A8B91bee51" # make sure to set the correct address of the contract that will be called
response_function = "setReadyToStart(bool)" # function to call on the contract
cooldown_period_blocks = 40 # how long to wait before the trap can be triggered again
min_number_of_operators = 1 # minimum number of operators required to trigger the trap
max_number_of_operators = 2 # maximum number of operators that can trigger the trap
block_sample_size = 10 # how many blocks to sample to determine the price of the trap
private_trap = true # if you want to only have whitelisted operators run your trap
whitelist = [] # whitelist your operator addresses here
